### ISSUE TITLE
Proposed additions to material

### ISSUE THREAD

**Issue by OliverWoolland** [UoMResearchIT/docker-introduction-archive#8]
Meta issue for additions to the course material 

- [x] UoMResearchIT/docker-introduction-archive#9
- [x] UoMResearchIT/docker-introduction-archive#12
- [ ] UoMResearchIT/docker-introduction#21
